const propertiesData = [
    {
      "id": 1,
      "ciudad": "Barranquilla",
      "nombre": "Macarol",
      "categoria": "Apartamento",
      "precio_actual": 321100000,
      "precio_anterior": 435141509,
      "area": "80m²",
      "habitaciones": 3,
      "baños": 2,
      "parqueaderos": 1,
      "imagen": "/img/casa1.jpg",
      "latitud": 10.9639,
      "longitud": -74.7964,
      "descripcion": "Moderno apartamento en el corazón de Barranquilla, cerca de centros comerciales y zonas de interés."
    },
    {
      "id": 2,
      "ciudad": "Bogotá",
      "nombre": "Pinar de la Fontana",
      "categoria": "Casa",
      "precio_actual": 255000000,
      "precio_anterior": 315000000,
      "area": "58m²",
      "habitaciones": 2,
      "baños": 2,
      "parqueaderos": 0,
      "imagen": "/img/casa2.jpg",
      "latitud": 4.7110,
      "longitud": -74.0721,
      "descripcion": "Acogedora casa en Bogotá con excelente ubicación y acceso a transporte público."
    },
    {
      "id": 3,
      "ciudad": "Jamundí",
      "nombre": "Tangara",
      "categoria": "Apartamento",
      "precio_actual": 350000000,
      "precio_anterior": 400000000,
      "area": "100m²",
      "habitaciones": 2,
      "baños": 2,
      "parqueaderos": 1,
      "imagen": "/img/casa3.jpg",
      "latitud": 3.2630,
      "longitud": -76.5377,
      "descripcion": "Amplio apartamento en Jamundí con áreas sociales y excelente vista."
    },
    {
      "id": 4,
      "ciudad": "Rionegro",
      "nombre": "Alejandría",
      "categoria": "Lote",
      "precio_actual": 190000000,
      "precio_anterior": 240000000,
      "area": "54m²",
      "habitaciones": 2,
      "baños": 2,
      "parqueaderos": 1,
      "imagen": "/img/casa4.jpg",
      "latitud": 6.1532,
      "longitud": -75.3740,
      "descripcion": "Excelente lote en zona en desarrollo de Rionegro, ideal para proyecto de construcción."
    }
  ];